# Azure DevOps Pipeline for Houseiana Backend
# Builds and deploys ASP.NET 8 application to Azure App Service

trigger:
- master
- main

variables:
  buildConfiguration: 'Release'
  azureServiceConnection: 'Azure-ServiceConnection'
  webAppName: 'Houseiana'
  resourceGroupName: 'Houseiana_group'
  dotNetFramework: 'net8.0'
  dotNetVersion: '8.0.x'
  workingDirectory: '.'

stages:
- stage: Build
  displayName: 'Build Stage'
  jobs:
  - job: Build
    displayName: 'Build Job'
    pool:
      vmImage: 'ubuntu-latest'

    steps:
    - task: UseDotNet@2
      displayName: 'Use .NET 8 SDK'
      inputs:
        packageType: 'sdk'
        version: $(dotNetVersion)
        installationPath: $(Agent.ToolsDirectory)/dotnet

    - task: DotNetCoreCLI@2
      displayName: 'Restore NuGet packages'
      inputs:
        command: 'restore'
        projects: '**/*.csproj'
        workingDirectory: $(workingDirectory)

    - task: DotNetCoreCLI@2
      displayName: 'Build application'
      inputs:
        command: 'build'
        projects: '**/*.csproj'
        arguments: '--configuration $(buildConfiguration) --no-restore'
        workingDirectory: $(workingDirectory)

    - task: DotNetCoreCLI@2
      displayName: 'Run unit tests'
      inputs:
        command: 'test'
        projects: '**/*Tests/*.csproj'
        arguments: '--configuration $(buildConfiguration) --no-build --verbosity normal --collect:"XPlat Code Coverage" --results-directory $(Agent.TempDirectory)'
        workingDirectory: $(workingDirectory)
      continueOnError: true

    - task: DotNetCoreCLI@2
      displayName: 'Publish application'
      inputs:
        command: 'publish'
        publishWebProjects: true
        arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'
        workingDirectory: $(workingDirectory)

    - task: PublishBuildArtifacts@1
      displayName: 'Publish artifacts'
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'

- stage: Deploy
  displayName: 'Deploy Stage'
  dependsOn: Build
  condition: succeeded()
  jobs:
  - deployment: Deploy
    displayName: 'Deploy Job'
    environment: 'Production'
    pool:
      vmImage: 'ubuntu-latest'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureWebApp@1
            displayName: 'Deploy to Azure App Service'
            inputs:
              azureSubscription: $(azureServiceConnection)
              appType: 'webAppLinux'
              appName: $(webAppName)
              resourceGroupName: $(resourceGroupName)
              package: '$(Pipeline.Workspace)/drop/*.zip'
              runtimeStack: 'DOTNETCORE|8.0'
              appSettings: |
                -ASPNETCORE_ENVIRONMENT Production
                -WEBSITES_ENABLE_APP_SERVICE_STORAGE false
                -WEBSITES_PORT 4000